databases:
  - name: postgres
    databaseName: HealthTracker_development
    user: health_tracker
    plan: free

services:
  - type: web
    name: health_tracker
    runtime: ruby
    plan: free
    buildCommand: "./render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
